### ISSUE TITLE
When to release the codes？

### ISSUE THREAD

**Issue by XuWWJ** [BookerDeWitt/GFN-IJCV#1]

**Comment by jeejeelee** [comment]
http://xinyizhang.tech/bmvc2018/

**Comment by BookerDeWitt** [comment]
@XuWWJ 
Thanks for your interest.

I'm now working on the camera-ready of the CVPR2020, and I will release the code about 20, March.

The link provided by @jeejeeli is the source code of our BMVC paper, and this time we will also release the code for dehazing+SR and deraining+SR as well.
